"""Reproduce the fixed-point time-domain FIR lookup; requires NumPy/SciPy."""
from pathlib import Path
import numpy as np
from scipy.signal import firwin

h = firwin(641, 8.0, window=("kaiser", 5.0), fs=1000.0)
q = np.rint(h[320:] / h[320] * 32767).astype(int)
lines = ["/* Generated by Tools/generate-resampler-kernel.py using scipy.signal.firwin.",
         " * 8 Hz cutoff, Kaiser beta=5, support +/-320 ms, 1 ms lookup grid.",
         " * Runtime normalizes the sampled kernel for unity DC gain. */",
         "static const int16_t kernel[321] = {"]
for i in range(0, len(q), 12):
    lines.append("    " + ", ".join(map(str, q[i:i+12])) + ",")
lines.append("};")
(Path(__file__).resolve().parents[1] / "App/Src/resampler_kernel.h").write_text(
    "\n".join(lines) + "\n", encoding="ascii")
